name: Prepare Environment for Android

inputs:
  GOOGLE_AUTH_WEB_CLIENT_ID:
    required: true
    description: ""
  BASE_URL:
    required: true
    description: ""
  FIREBASE_KEY:
    required: true
    description: ""
  ANDROID_FIREBASE_CLIENT_ID:
    required: true
    description: ""
  os:
    required: true
    description: ""
  working-directory:
    required: false
    description: ""
    default: '.'

description: ""

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ inputs.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ inputs.os }}-gradle-

    - name: Update production.properties
      env:
        AUTH_WEB_CLIENT_ID: ${{ inputs.AUTH_WEB_CLIENT_ID }}
        BASE_URL: ${{ inputs.BASE_URL }}
        FIREBASE_KEY: ${{ inputs.FIREBASE_KEY }}
        ANDROID_FIREBASE_CLIENT_ID: ${{ inputs.ANDROID_FIREBASE_CLIENT_ID }}
      shell: bash
      run: |
        echo GOOGLE_AUTH_WEB_CLIENT_ID="${AUTH_WEB_CLIENT_ID}" > ./composeApp/production.properties
        echo BASE_URL="BASE_URL" > ./production.properties
        echo FIREBASE_KEY="FIREBASE_KEY" > ./production.properties
        echo ANDROID_FIREBASE_CLIENT_ID="ANDROID_FIREBASE_CLIENT_ID" > ./production.properties

    - name: Update staging.properties
      env:
        AUTH_WEB_CLIENT_ID: ${{ inputs.AUTH_WEB_CLIENT_ID }}
        BASE_URL: ${{ inputs.BASE_URL }}
        FIREBASE_KEY: ${{ inputs.FIREBASE_KEY }}
        ANDROID_FIREBASE_CLIENT_ID: ${{ inputs.ANDROID_FIREBASE_CLIENT_ID }}
      shell: bash
      run: |
        echo GOOGLE_AUTH_WEB_CLIENT_ID="${AUTH_WEB_CLIENT_ID}" > ./composeApp/staging.properties
        echo BASE_URL="BASE_URL" > ./staging.properties
        echo FIREBASE_KEY="FIREBASE_KEY" > ./staging.properties
        echo ANDROID_FIREBASE_CLIENT_ID="ANDROID_FIREBASE_CLIENT_ID" > ./staging.properties
