#!/bin/sh

OUTPUT="/tmp/output"

echo "Running pre-push ktlint check..."
./gradlew ktlintCheck > OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat OUTPUT
  rm OUTPUT
  echo "***********************************************"
  echo "                 Ktlint failed                 "
  echo "       You may attempt to use gradle task      "
  echo "            ./gradlew ktlintFormat             "
  echo "***********************************************"
  exit $EXIT_CODE
fi

echo "Running pre-push detekt check..."
./gradlew detekt > OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat OUTPUT
  rm OUTPUT
  echo "***********************************************"
  echo "                 Detekt failed                 "
  echo "***********************************************"
  exit $EXIT_CODE
fi

echo "Running pre-push swiftlint check..."
cd iosApp
cd iosApp
swiftlint > OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat OUTPUT
  rm OUTPUT
  echo "***********************************************"
  echo "                 Swiftlint failed                 "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm OUTPUT
