ktor:
    application:
        modules:
            - pl.msiwak.ApplicationKt.module
    development: "$IS_DEVELOPMENT"
    deployment:
        port: 8080
storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "$DATABASE_URL"
    user: "$DATABASE_USER"
    password: "$DATABASE_PASSWORD"

apiKey: "$API_KEY"
