name: Prepare Production properties

inputs:
  secrets:
    required: true
    type: string
  working-directory:
    required: false
    type: string
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Update production.properties
      env:
        AUTH_WEB_CLIENT_ID: ${{ secrets.AUTH_WEB_CLIENT_ID }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: |
        echo GOOGLE_AUTH_WEB_CLIENT_ID="${AUTH_WEB_CLIENT_ID}" > ${{ inputs.working-directory }}/androidApp/production.properties
        echo BASE_URL="BASE_URL" > ${{ inputs.working-directory }}/production.properties
