services:
  database:
    image: postgres
    restart: always
    env_file:
      .env
    networks:
      - network1
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - network1
    ports:
      - "8080:8080"
networks:
  network1:
    driver: bridge
volumes:
  data: