name: Android CI

on:
  push:
    branches: [ "develop" ,"master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo "Setting up JDK"
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Update production.properties
      env:
        GOOGLE_AUTH_WEB_CLIENT_ID: ${{ secrets.GOOGLE_AUTH_WEB_CLIENT_ID }}
      run: echo GOOGLE_AUTH_WEB_CLIENT_ID="GOOGLE_AUTH_WEB_CLIENT_ID" > ./androidApp/production.properties

    - name: Update debug.properties
      env:
        GOOGLE_AUTH_WEB_CLIENT_ID: ${{ secrets.GOOGLE_AUTH_WEB_CLIENT_ID }}
      run: echo GOOGLE_AUTH_WEB_CLIENT_ID="GOOGLE_AUTH_WEB_CLIENT_ID" > ./androidApp/debug.properties

    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'release.jks'
        fileDir: '/home/runner/work/multiplatform/multiplatform/signing/'
        encodedString: ${{ secrets.SIGNING_RELEASE }}

    - name: Build APK
      run: ./gradlew assembleRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
