name: Android CI

on:
  push:
    branches: [ "develop" ,"master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - run: echo "Setting up JDK"
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Update release.properties
      env:
        AUTH_WEB_CLIENT_ID: ${{ secrets.AUTH_WEB_CLIENT_ID }}
      run: echo GOOGLE_AUTH_WEB_CLIENT_ID="${AUTH_WEB_CLIENT_ID}" > ./androidApp/release.properties

    - name: Update debug.properties
      env:
        AUTH_WEB_CLIENT_ID: ${{ secrets.AUTH_WEB_CLIENT_ID }}
      run: echo GOOGLE_AUTH_WEB_CLIENT_ID="${AUTH_WEB_CLIENT_ID}" > ./androidApp/debug.properties

    - name: Update release.properties
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
      run: echo BASE_URL="BASE_URL" > ./release.properties

    - name: Update debug.properties
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
      run: echo BASE_URL="BASE_URL" > ./debug.properties

    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'release.jks'
        fileDir: '/home/runner/work/multiplatform/multiplatform/signing/'
        encodedString: ${{ secrets.SIGNING_RELEASE }}

    - name: Decode debug Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'debug.jks'
        fileDir: '/home/runner/work/multiplatform/multiplatform/signing/'
        encodedString: ${{ secrets.SIGNING_DEBUG }}

    - name: Build APK
      run: ./gradlew :androidApp:assembleRelease -x test
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
