package pl.msiwak.multiplatform.navigator

const val WELCOME_SCREEN_ROUTE = "welcome_screen"
const val REGISTRATION_SCREEN_ROUTE = "registration_screen"
const val DASHBOARD_SCREEN_ROUTE = "dashboard_screen"
const val SUMMARY_SCREEN_ROUTE = "summary_screen"
const val SETTINGS_SCREEN_ROUTE = "settings_screen"
const val ADD_CATEGORY_SCREEN_ROUTE = "add_category_screen"
const val CATEGORY_SCREEN_ROUTE = "category_details_screen"
const val EXERCISE_SCREEN_ROUTE = "exercise_screen"
const val EXERCISE_CHART_SCREEN_ROUTE = "exercise_chart_screen"
const val LANGUAGE_SCREEN_ROUTE = "language_screen"
const val UNIT_SCREEN_ROUTE = "unit_screen"
const val FORCE_UPDATE_SCREEN_ROUTE = "force_update_screen"
const val VERIFY_EMAIL_SCREEN_ROUTE = "verify_email_screen"
